
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lijwchxzizorxtrxszwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpandjaHh6aXpvcnh0cnhzend4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODkyMDgsImV4cCI6MjA1OTM2NTIwOH0.bTrcb3sDPE6fWbKqWH4sKSyLX72q9FTXDxDYP_nKEBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
